version: '3.4'

services:
  kafka:
    restart: always
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
    environment:
      - KAFKA_LISTENERS=CONTROLLER://localhost:9091,PLAINTEXT://0.0.0.0:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://192.168.1.7:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - CLUSTER_ID=XyZBQ3-GTvKH2qNfP7X33A
      - KAFKA_NODE_ID=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9091
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER

  redis:
    restart: always
    image: redis/redis-stack:latest
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - /local-data/:/data

  # pubsub:
  #   restart: always
  #   image: redis/redis-stack:latest
  #   ports:
  #     - 6380:6379
  #     - 8002:8001
  #   volumes:
  #     - /local-data/:/data

  sessionservice:
    image: sessionservice
    restart: always
    build:
      context: .
      dockerfile: ./apps/session-service/Dockerfile
    depends_on:
      - sessionStore
    environment:
      - REDIS_HOST=sessionStore
      - REDIS_PORT=6379
      - NODE_ENV=production
    ports:
      - 5000:5000

  backend:
    image: backend
    restart: always
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile
    depends_on:
      - kafka
    environment:
      - REDIS_PORT=6379
      - KAFKA_HOST=kafka
      - NODE_ENV=production
      - MONGODB_URL=mongodb://host.docker.internal:27017/chatdb
      - JWT_USER_TOKEN_SECRET_KEY=c8de8aa33f43ce16cd67267acf47c6d253d13f78d27104f29e0e0a98f76d6c4216c0e452d6a071b616aeb4a6a64a1a3fd80f29e050ac568510ad8bc33ba60a30
      - JWT_ACCESS_TOKEN_SECRET_KEY=8fe4dd1a542ae836b9715e7bc3b8c2f950f886d63c61bbb1fa8cd28f1c020ab78327a7ee69b9d7db325e451e68f959ab779f5e35b1806cc7459749520e39a27f
    ports:
      - 4000:4000
      - 27017:27017

  socket-service:
    image: socket-service
    restart: always
    build:
      context: .
      dockerfile: ./apps/socket-service/Dockerfile
    depends_on:
      - kafka
    environment:
      - REDIS_PORT=6379
      - KAFKA_HOST=kafka
      - NODE_ENV=production
    ports:
      - 3002:3002

  gateway:
    restart: always
    image: gateway
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    # depends_on:
    #   - pubsub
    #   - kafka
    environment:
      - SOCKET_SERVICE_URL=http://socket-service
      - SESSION_SERVICE_URL=http://sessionservice
      - BACKEND_URL=http://backend
      - NODE_ENV=production
    ports:
      - 3001:3001
