services:
  sessionservice:
    image: ${ECR_REGISTRY}/chatvia-session-service:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ./apps/session-service/Dockerfile

  backend:
    image: ${ECR_REGISTRY}/chatvia-backend-service:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ./apps/backend/Dockerfile

  socket-service:
    image: ${ECR_REGISTRY}/chatvia-socket-service:${IMAGE_TAG:-latest}
    build:
      context: .
      dockerfile: ./apps/socket-service/Dockerfile

  traefik:
    image: ${ECR_REGISTRY}/chatvia-gateway:${IMAGE_TAG:-latest}
    build:
      context: ./traefik
      dockerfile: Dockerfile
