import "./styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthContext from "../context/AuthContext";
import { SockerProvider } from "../context/SocketProvider";
import { ThemeProvider } from "next-themes";
import { ThemeManager } from "@features/ThemeManager";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({ children }: { children: React.ReactNode }): JSX.Element {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* <script src="https://unpkg.com/react-scan/dist/auto.global.js" /> */}
      </head>
      <body className={inter.className}>
        <ThemeProvider enableSystem>
          <ThemeManager />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
