import "./styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AuthContext from "../context/AuthContext";
import { SockerProvider } from "../context/SocketProvider";
import { ThemeProvider } from "next-themes";
import { ThemeManager } from "../components/ThemeManager";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContext>
          <SockerProvider>
            <ThemeProvider enableSystem>
              <ThemeManager />
              {children}
            </ThemeProvider>
          </SockerProvider>
        </AuthContext>
      </body>
    </html>
  );
}
