import "./styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SockerProvider } from "../context/SocketProvider";
import AuthContext from "../context/AuthContext";
import Modal from "../components/ui/Modal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html data-theme="darktheme" lang="en">
      <AuthContext>
        <SockerProvider>
          <body className={inter.className}>
            <Modal />
            {children}
          </body>
        </SockerProvider>
      </AuthContext>
    </html>
  );
}
